In [13]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import operator

In [14]:
def createDataSet():
    group = np.array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    labels=['A','A','B','B']
    return group, labels

In [15]:
group, labels=createDataSet()

In [115]:
def classify0(inX,dataSet,labels,k):
    dataSetSize = dataSet.shape[0]
#     print(dataSetSize)
    diffMat = np.tile(inX, (dataSetSize,1))-dataSet
#     print(np.tile(inX, (dataSetSize,1)))
#     print(diffMat)
    sqDiffMat = diffMat **2
#     print(sqDiffMat)
    sqDistances = sqDiffMat.sum(axis=1)
    distances=sqDistances**0.5
#     print(distances)
    sortedDistIndicies = distances.argsort()
#     print(sortedDistIndicies)
    classCount={}
    for i in range(k):
        votellabel=labels[sortedDistIndicies[i]]
        print(sortedDistIndicies[i])
        classCount[votellabel]= classCount.get(votellabel,0)+1
        print(classCount)
    i=classCount.values()
    sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1),reverse=True)
    return sortedClassCount[0]

In [116]:
classify0([0,0],group,labels,3)

2
{'B': 1}
3
{'B': 2}
1
{'B': 2, 'A': 1}


('B', 2)

In [46]:
def file2matrix(filename):
    love_dictionary={'largeDoses':3, 'smallDoses':2, 'didntLike':1}
    fr = open(filename)
    array0Lines = fr.readlines()
    numberOfLines = len(array0Lines)
    returnMat =np.zeros((numberOfLines,3))
    classLabelVector = []
    index = 0
    print(numberOfLines)
    for line in array0Lines:
        line = line.strip()
        listFromLine = line.split('\t')
        returnMat[index,:] = listFromLine[0:3]
        #print(returnMat)
        if (listFromLine[-1].isdigit()):
            classLabelVector.append(int(listFromLine[-1]))
        else:
            classLabelVector.append(love_dictionary.get(listFromLine[-1]))
        index+=1
    return returnMat,classLabelVector

In [ ]:
datingData, datingLabels = file2matrix('datingTestSet.txt')

In [ ]:
classify0((inArr-minVals)/ranges, normMat, datingLabels,3)

In [75]:
def autoNorm(dataSet):
    minVals = dataSet.min(0)
    maxVals = dataSet.max(0)
    ranges = maxVals - minVals
    normDataSet = np.zeros(np.shape(dataSet))
    m = dataSet.shape[0]
    normDataSet = dataSet - np.tile(minVals, (m,1))
    print(np.tile(minVals, (m,1)))
    normDataSet = normDataSet/np.tile(ranges, (m,1))
    return normDataSet, ranges, minVals

In [77]:
normMat,ranges,minVals = autoNorm(datingData)

[[0.       0.       0.001156]
 [0.       0.       0.001156]
 [0.       0.       0.001156]
 ...
 [0.       0.       0.001156]
 [0.       0.       0.001156]
 [0.       0.       0.001156]]


In [79]:
def classify0(inX,dataSet,labels,k):
    dataSetSize = dataSet.shape[0]
    print(dataSetSize)
    diffMat = np.tile(inX, (dataSetSize,1))-dataSet
    print(diffMat)
    sqDiffMat = diffMat **2
    sqDistances = sqDiffMat.sum(axis=1)
    distances=sqDistances**0.5
    sortedDistIndicies = distances.argsort()
    classCount={}
    for i in range(k):
        votellabel=labels[sortedDistIndicies[i]]
        classCount[votellabel]= classCount.get(votellabel,0)+1
    i=classCount.values()
    sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1),reverse=True)
    return sortedClassCount[0][0]

array([[0.44832535, 0.39805139, 0.56233353],
       [0.15873259, 0.34195467, 0.98724416],
       [0.28542943, 0.06892523, 0.47449629],
       ...,
       [0.29115949, 0.50910294, 0.51079493],
       [0.52711097, 0.43665451, 0.4290048 ],
       [0.47940793, 0.3768091 , 0.78571804]])

In [80]:
classify0([0,0],group,labels,3)

4
[[-1.  -1.1]
 [-1.  -1. ]
 [ 0.   0. ]
 [ 0.  -0.1]]


'B'

In [1]:
from sklearn.naive_bayes import GaussianNB

In [5]:
print(GaussianNB)

<class 'sklearn.naive_bayes.GaussianNB'>
