In [1]:
from keras_preprocessing.text import Tokenizer

In [2]:
t = Tokenizer()

In [3]:
text ='''
경마장에 있는 말이 뛰고 있다.\n
그의 말이 법이다. \n
가는 말이 고와야 오는 말이 곱다.\n'''

In [5]:
t.fit_on_texts([text])
encode = t.texts_to_sequences([text])

In [6]:
vocab_size = len(t.word_index) +1

In [7]:
print('단어 집합의 크기 : %d'%vocab_size)

단어 집합의 크기 : 12


In [8]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [11]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
print('훈련 데이터의 수 : %d'%len(sequences))

훈련 데이터의 수 : 11


In [14]:
# 모든 데이터에서 길이가 가장 긴 데이터의 길이 출력
print(max(len(l) for l in sequences))

6


In [16]:
from keras.preprocessing.sequence import pad_sequences
sequences = pad_sequences(sequences, maxlen =6, padding='pre')

Using TensorFlow backend.


In [17]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [18]:
import numpy as np
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [19]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [20]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [22]:
from keras.utils import to_categorical

In [23]:
y = to_categorical(y,num_classes = vocab_size)

In [25]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [31]:
from keras.layers import Embedding, Dense, SimpleRNN
from keras.models import Sequential

model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=5))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.fit(X,y,epochs = 200, verbose = 2)

W0821 14:32:24.553462  2752 deprecation.py:323] From c:\users\fire7\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0821 14:32:24.815670  2752 deprecation_wrapper.py:119] From c:\users\fire7\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/200
 - 1s - loss: 2.5039 - acc: 0.0000e+00
Epoch 2/200
 - 0s - loss: 2.4895 - acc: 0.0000e+00
Epoch 3/200
 - 0s - loss: 2.4776 - acc: 0.0000e+00
Epoch 4/200
 - 0s - loss: 2.4653 - acc: 0.0909
Epoch 5/200
 - 0s - loss: 2.4529 - acc: 0.0909
Epoch 6/200
 - 0s - loss: 2.4403 - acc: 0.1818
Epoch 7/200
 - 0s - loss: 2.4274 - acc: 0.2727
Epoch 8/200
 - 0s - loss: 2.4143 - acc: 0.3636
Epoch 9/200
 - 0s - loss: 2.4008 - acc: 0.3636
Epoch 10/200
 - 0s - loss: 2.3868 - acc: 0.3636
Epoch 11/200
 - 0s - loss: 2.3722 - acc: 0.4545
Epoch 12/200
 - 0s - loss: 2.3569 - acc: 0.4545
Epoch 13/200
 - 0s - loss: 2.3408 - acc: 0.4545
Epoch 14/200
 - 0s - loss: 2.3239 - acc: 0.4545
Epoch 15/200
 - 0s - loss: 2.3061 - acc: 0.4545
Epoch 16/200
 - 0s - loss: 2.2873 - acc: 0.4545
Epoch 17/200
 - 0s - loss: 2.2677 - acc: 0.3636
Epoch 18/200
 - 0s - loss: 2.2469 - acc: 0.3636
Epoch 19/200
 - 0s - loss: 2.2252 - acc: 0.3636
Epoch 20/200
 - 0s - loss: 2.2026 - acc: 0.3636
Epoch 21/200
 - 0s - loss: 2.1790 - a

Epoch 171/200
 - 0s - loss: 0.1443 - acc: 1.0000
Epoch 172/200
 - 0s - loss: 0.1417 - acc: 1.0000
Epoch 173/200
 - 0s - loss: 0.1392 - acc: 1.0000
Epoch 174/200
 - 0s - loss: 0.1367 - acc: 1.0000
Epoch 175/200
 - 0s - loss: 0.1343 - acc: 1.0000
Epoch 176/200
 - 0s - loss: 0.1320 - acc: 1.0000
Epoch 177/200
 - 0s - loss: 0.1297 - acc: 1.0000
Epoch 178/200
 - 0s - loss: 0.1275 - acc: 1.0000
Epoch 179/200
 - 0s - loss: 0.1253 - acc: 1.0000
Epoch 180/200
 - 0s - loss: 0.1232 - acc: 1.0000
Epoch 181/200
 - 0s - loss: 0.1212 - acc: 1.0000
Epoch 182/200
 - 0s - loss: 0.1191 - acc: 1.0000
Epoch 183/200
 - 0s - loss: 0.1172 - acc: 1.0000
Epoch 184/200
 - 0s - loss: 0.1152 - acc: 1.0000
Epoch 185/200
 - 0s - loss: 0.1134 - acc: 1.0000
Epoch 186/200
 - 0s - loss: 0.1115 - acc: 1.0000
Epoch 187/200
 - 0s - loss: 0.1097 - acc: 1.0000
Epoch 188/200
 - 0s - loss: 0.1080 - acc: 1.0000
Epoch 189/200
 - 0s - loss: 0.1063 - acc: 1.0000
Epoch 190/200
 - 0s - loss: 0.1046 - acc: 1.0000
Epoch 191/200
 - 0s 

In [53]:
def sentencs_generation(model, t, current_word, n):
    init_word = current_word
    sentence  = ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        result = model.predict_classes(encoded, verbose=0)
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word
    sentence = init_word + sentence
    return sentence

In [54]:
print(sentencs_generation(model, t, '경마장에',4))

경마장에 있는 말이 뛰고 있다


In [55]:
print(sentencs_generation(model,t, '그의', 2))

그의 말이 법이다


In [56]:
print(sentencs_generation(model, t, '가는',5))

가는 말이 고와야 오는 말이 곱다


In [63]:
print(sentencs_generation(model,t, '뛰고', 3))

뛰고 말이 법이다 말이
