In [1]:
import numpy as np

In [2]:
x = np.array(5)
x.ndim

0

In [4]:
x = np.array([32,5,3,43,27])
x.ndim

1

In [7]:
x = np.array([[32,5,3,43,27],[32,5,3,43,27],[32,5,3,43,27]])
x.ndim

2

In [16]:
x = np.array([[[32,5,3,43,27],[32,5,3,43,27],[32,5,3,43,27],[32,5,3,43,27],[32,5,3,43,27],[32,5,3,43,27]],
             [[32,5,3,43,27],[32,5,3,43,27],[32,5,3,43,27],[32,5,3,43,27],[32,5,3,43,27],[32,5,3,43,27]]])
x.ndim

3

In [17]:
x.shape

(2, 6, 5)

In [30]:
a = np.array([5,5,5,5,5,5,5,5,5,5,5,5,5,5,5])
len(a)

15

In [31]:
a.reshape((3,5))

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [33]:
a.reshape((3,-1))

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [34]:
b = np.ones(20)

In [36]:
b.reshape(2,2,5)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [37]:
b.reshape(-1,2,5)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [39]:
np.ravel(b)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [51]:
b.reshape((2,2,-1)).sum(axis=2)

array([[5., 5.],
       [5., 5.]])

In [52]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
c.sum()

45

In [55]:
c.sum(axis=0)

array([12, 15, 18])

In [56]:
c.sum(axis=1)

array([ 6, 15, 24])

In [57]:
d = np.array([1,2,3,4,5,6,7,8])

In [58]:
d = d.reshape(2,2,-1)

In [61]:
for i in range(3):
    print(d.sum(axis=i))
    print()

[[ 6  8]
 [10 12]]

[[ 4  6]
 [12 14]]

[[ 3  7]
 [11 15]]



In [66]:
a = np.array([1,2])
b = np.array([10,20])

In [68]:
b@a

50

In [72]:
np.squeeze([[[1,1]],[[2,2]],[[3,3]]]).ndim

2

In [73]:
np.squeeze([[[1]],[[2]],[[3]]]).ndim

1